import "@/styles/tailwind.css";

import type { Metadata } from "next";
import type { FC, PropsWithChildren } from "react";
import { Toaster } from "sonner";

export const metadata: Metadata = {
	title: "Flow Cat",
	description: "Generated by Next.js",
};

const Layout: FC<PropsWithChildren> = ({ children }) => (
	<html lang="en">
		<body className="w-screen h-screen">
			{children}
			<Toaster richColors />
		</body>
	</html>
);

export default Layout;
