import "@/styles/tailwind.css";

import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import type { FC, PropsWithChildren } from "react";
import { Toaster } from "sonner";

export const metadata: Metadata = {
	title: "Flow Cat",
	description: "Generated by Next.js",
};

const Layout: FC<PropsWithChildren> = ({ children }) => (
	<html lang="en" suppressHydrationWarning>
		<body className="w-screen h-screen">
			<ThemeProvider
				attribute="class"
				defaultTheme="system"
				enableSystem
				disableTransitionOnChange
			>
				{children}
				<Toaster richColors />
			</ThemeProvider>
		</body>
	</html>
);

export default Layout;
