import "@/styles/tailwind.css";

import { DictionaryProviderComponent } from "@/components/providers/dictionary";
import { getLangData } from "@/services/dictionary";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import type { FC, PropsWithChildren } from "react";
import { Toaster } from "sonner";

export const metadata: Metadata = {
	title: "Flow Cat",
	description: "Generated by Next.js",
};

const Layout: FC<PropsWithChildren> = async ({ children }) => {
	const langData = await getLangData();

	return (
		<html lang={langData.code} suppressHydrationWarning>
			<body className="w-screen h-screen">
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<DictionaryProviderComponent
						code={langData.code}
						dictionary={langData.dictionary}
					>
						{children}
						<Toaster richColors />
					</DictionaryProviderComponent>
				</ThemeProvider>
			</body>
		</html>
	);
};

export default Layout;
